# KNN IRIS DATASET

changing value of attribute n_neighbors in Class KNN

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np

In [83]:
ds = datasets.load_iris()
#knn = KNeighborsClassifier()
knn = KNeighborsClassifier(n_neighbors=4)

In [84]:
x=ds.data
y=ds.target

In [85]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [86]:
model = knn.fit(x_train,y_train)

In [87]:
y_pred = model.predict(x_test)

In [88]:
accuracy = metrics.accuracy_score(y_test,y_pred)

In [89]:
print("ACCURACY",accuracy)

ACCURACY 1.0


In [90]:
cm=metrics.confusion_matrix(y_test,y_pred)

In [91]:
print(cm)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [92]:
fp=cm.sum(axis=0)-np.diag(cm)
print(fp)
fn=cm.sum(axis=1)-np.diag(cm)
print(fn)
tp=np.diag(cm)
print(tp)
tn=cm.sum()-(fn+fp+tp)
print(tn)
accuracy=((tp+tn) / (tp+tn+fn+fp))
misclassification=(fp+fn)/(tp+tn+fp+fn)
sensitivity=tp/(tp+fn)
specificity=tn/(tn+fp)
precision=tp/(tp+fp)
fmeasure=(2*precision*sensitivity)/(precision+sensitivity)
fbeta=(1.25*precision*sensitivity)/(.25*precision+sensitivity)
print()
print(accuracy)
print(misclassification)
print(sensitivity)
print(specificity)
print(precision)
print(fmeasure)
print(fbeta)

[0 0 0]
[0 0 0]
[11 13  6]
[19 17 24]

[1. 1. 1.]
[0. 0. 0.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]


# KNN WINE DATASET

changing value of attribute n_neighbors in Class KNN

In [72]:
ds = datasets.load_wine()
# knn = KNeighborsClassifier()
knn = KNeighborsClassifier(n_neighbors=4)
x=ds.data
y=ds.target
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

model = knn.fit(x_train,y_train)

y_pred = model.predict(x_test)

accuracy = metrics.accuracy_score(y_test,y_pred)

print("ACCURACY",accuracy)

cm=metrics.confusion_matrix(y_test,y_pred)

print(cm)

fp=cm.sum(axis=0)-np.diag(cm)
print(fp)
fn=cm.sum(axis=1)-np.diag(cm)
print(fn)
tp=np.diag(cm)
print(tp)
tn=cm.sum()-(fn+fp+tp)
print(tn)
accuracy=((tp+tn) / (tp+tn+fn+fp))
misclassification=(fp+fn)/(tp+tn+fp+fn)
sensitivity=tp/(tp+fn)
specificity=tn/(tn+fp)
precision=tp/(tp+fp)
fmeasure=(2*precision*sensitivity)/(precision+sensitivity)
fbeta=(1.25*precision*sensitivity)/(.25*precision+sensitivity)
print()
print(accuracy)
print(misclassification)
print(sensitivity)
print(specificity)
print(precision)
print(fmeasure)
print(fbeta)

ACCURACY 0.75
[[12  2  0]
 [ 0 13  3]
 [ 1  3  2]]
[1 5 3]
[2 3 4]
[12 13  2]
[21 15 27]

[0.91666667 0.77777778 0.80555556]
[0.08333333 0.22222222 0.19444444]
[0.85714286 0.8125     0.33333333]
[0.95454545 0.75       0.9       ]
[0.92307692 0.72222222 0.4       ]
[0.88888889 0.76470588 0.36363636]
[0.90909091 0.73863636 0.38461538]
