In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
df=datasets.load_wine()
nb=GaussianNB()
print(df.feature_names)
print(df.target_names)
x=df.data
y=df.target
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)
model=nb.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
accuracy=metrics.accuracy_score(Y_test,Y_pred)
print("Accuracy",accuracy)
cm=metrics.confusion_matrix(Y_test,Y_pred)
print(cm)



['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['class_0' 'class_1' 'class_2']
Accuracy 0.9166666666666666
[[14  0  0]
 [ 2 13  1]
 [ 0  0  6]]


In [2]:
from sklearn.naive_bayes import GaussianNB
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
df=datasets.load_iris()
nb=GaussianNB()
print(df.feature_names)
print(df.target_names)
x=df.data
y=df.target
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)
model=nb.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
accuracy=metrics.accuracy_score(Y_test,Y_pred)
print("Accuracy",accuracy)
cm=metrics.confusion_matrix(Y_test,Y_pred)
print(cm)



['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
Accuracy 0.9666666666666667
[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [3]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
df=datasets.load_wine()
nb=GaussianNB()
print(df.feature_names)
print(df.target_names)
x=df.data
y=df.target
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)
model=nb.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
accuracy=metrics.accuracy_score(Y_test,Y_pred)
print("Accuracy",accuracy)
cm=metrics.confusion_matrix(Y_test,Y_pred)
print("Confusion matrix")
print(cm)
fp=cm.sum(axis=0)-np.diag(cm)
print(fp)
fn=cm.sum(axis=1)-np.diag(cm)
print(fn)
tp=np.diag(cm)
print(tp)
tn=cm.sum()-fn-fp-tp
print(tn)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['class_0' 'class_1' 'class_2']
Accuracy 0.9166666666666666
Confusion matrix
[[14  0  0]
 [ 2 13  1]
 [ 0  0  6]]
[2 0 1]
[0 3 0]
[14 13  6]
[20 20 29]
